### ISSUE TITLE
Bug: when using Vulpera 'Make Camp' ability

### ISSUE THREAD

**Issue by Jahfry** [SanjoSolutions/PasteLinkIntoMacro#1]
Notes: 

* I was in the room where you have portals to the 3 Radiant Echoes zones. 
   * 'Make Camp' probably shouldn't work in this room
   * 'Make Camp' works just OUTSIDE this room in the main Dalaran (Legion) city **without causing the LUA error**
* I haven't actually used the addon for anything yet, just installed it to check it out 

### Repro:
* Press 'Make Camp'
* Get this error:

```
2x [ADDON_ACTION_FORBIDDEN] AddOn 'PasteLinkIntoMacro' tried to call the protected function 'UseAction()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `UseAction'
[string "@Blizzard_FrameXML/Mainline/SecureTemplates.lua"]:342: in function `handler'
[string "@Blizzard_FrameXML/Mainline/SecureTemplates.lua"]:667: in function <...ddOns/Blizzard_FrameXML/Mainline/SecureTemplates.lua:649>
[string "@Blizzard_FrameXML/Mainline/SecureTemplates.lua"]:681: in function <...ddOns/Blizzard_FrameXML/Mainline/SecureTemplates.lua:674>
[string "@Blizzard_FrameXML/Mainline/SecureTemplates.lua"]:723: in function `SecureActionButton_OnClick'
[string "@Blizzard_ActionBar/Mainline/ActionButton.lua"]:1438: in function <Blizzard_ActionBar/Mainline/ActionButton.lua:1408>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@Blizzard_FrameXML/SecureHandlers.lua"]:266: in function <Blizzard_FrameXML/SecureHandlers.lua:263>
[string "=[C]"]: ?
[string "@Blizzard_FrameXML/SecureHandlers.lua"]:296: in function <Blizzard_FrameXML/SecureHandlers.lua:279>
[string "=(tail call)"]: ?

Locals:
_ = Frame {
}
event = "ADDON_ACTION_FORBIDDEN"
events = <table> {
}
``` 
![pastelinkintomacro](https://github.com/user-attachments/assets/ed5b1cf5-df45-4087-bc9e-7d8de6aa7e6d)

**Comment by SanjoSolutions** [comment]
Sorry for that. I'm currently not actively developing the addons. So I would just recommend to disable the add-on. Thanks for reporting.

As far as I recall, I have debugged a similar kind of error and wasn't able to figure out how to fix it (if it's even possible from the add-on side).

**Comment by Jahfry** [comment]
Roger, closing, thanks for quick reply :)
